---

  - name: Import ubuntu/debian Docker install
    include: ub_deb.yml
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

  - name: Import centos/rh Docker install
    include: cen_rh.yml
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' 

  - name: Install docker-py
    pip: name={{ item }} state=latest
    with_items:
      - docker-py

  - name: Start Docker
    service: name=docker state=restarted enabled=yes

  - name: Create /opt/upload dir
    file: path=/opt/upload state=directory mode=0666

  - name: Run docker SFTP server
    shell: docker run -p 2222:22 -v /opt/upload:/home/foo/upload -d atmoz/sftp foo:pass
